services:
  postgres-container:
    image: postgres:16
    container_name: postgres-container
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: 
      context: ./backend/photo-map
      dockerfile: Dockerfile.dev
    container_name: photomap-backend
    env_file: .env
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8092
      - APP_UPLOAD_DIR=/photomap/storage/uploads
      - APP_BASE_URL=https://api.personalphotomap.co.uk
      - JAVA_OPTS=-Xmx1g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat
    ports:
      - "8092:8092"
    volumes:
      - ./storage:/photomap/storage
    depends_on:
      - postgres-container

volumes:
  postgres-data:

