# This file is only used for local development.

# Step 1: Build the Backend
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copy necessary files for the build
COPY pom.xml .
COPY src ./src

# Build the JAR file
RUN mvn clean package -DskipTests

# Step 2: Run the Backend
FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

# Create upload directory with proper permissions
RUN mkdir -p /photomap/storage/uploads && chmod 755 /photomap/storage/uploads

# Copy the generated JAR from the build stage
COPY --from=build /app/target/*.jar app.jar

# Copy application.properties
COPY src/main/resources/application.properties .

EXPOSE 8092
ENTRYPOINT ["java", "-jar", "app.jar"]